[book]
authors = ["nicknamenamenick","Zeglius"]
language = "en"
multilingual = false
src = "src"
title = "Bazzite Documentation"

[build]
use-default-preprocessors = false
create-missing = false

[preprocessor.links]

[output.html]
git-repository-url="https://github.com/ublue-os/bazzite"
edit-url-template = "https://github.com/ublue-os/bazzite/edit/main/docs/{path}"

[preprocessor.youtube-embed]
command = "python ./preprocessors/youtube-embed.py"

[preprocessor.replace-urls]
command = "python ./preprocessors/replace-urls.py"
after = ["youtube-embed"]
ignore = ["Introduction*"]

[preprocessor.replace-urls.mappings]
"https://universal-blue.discourse.group/docs?topic=561" = "/Introduction.html"

[preprocessor.gettext]
after = ["links"]