on:
  workflow_call:
  workflow_dispatch:
    inputs:
      handwritten:
        description: 'Small changelog about changes in this build:'
      target:
        description: 'Release Branch (e.g., testing). Defaults to branch name.'
permissions:
  contents: write

name: Generate Release
jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last 500 commits (for <commits> to work)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 500

      - name: Get target
        id: get-target
        run: |
          TARGET="${{ github.event.inputs.target || github.ref }}"
          TARGET="${TARGET##*/}"
          if [ "$TARGET" = "main" ]; then
            TARGET="stable"
          fi
          echo "target=$TARGET" >> $GITHUB_OUTPUT
      
      - name: Generate Release Text
        id: generate-release
        run: |
          python3 ./.github/workflows/changelog.py \
            "${{ steps.get-target.outputs.target }}" \
            ./output.env ./changelog.md --workdir . --handwritten "${{ github.event.inputs.handwritten }}"
          source ./output.env
          echo "title=${TITLE}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2
        with:
          name: ${{ steps.generate-release.outputs.title }}
          tag_name: ${{ steps.generate-release.outputs.tag }}
          body_path: ./changelog.md
          make_latest: ${{ steps.get-target.outputs.target == 'stable' }}
          prerelease: ${{ steps.get-target.outputs.target != 'stable' }}
